pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Denforcer.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
        }
        stage('InProgress') {
            steps {
                sh 'GitPipeline InProgress'
            }
        }
        stage('Completed') {
            steps {
                echo 'GitPipeline Completed'
            }
        }
    }
}
